package models

import "github.com/vitaliiPsl/crappy-adk/kit"

func DefaultModels() map[string][]kit.ModelConfig {
	return map[string][]kit.ModelConfig{
		ProviderAnthropic: anthropicModels(),
		ProviderOpenAI:    openaiModels(),
		ProviderGoogle:    googleModels(),
	}
}

func anthropicModels() []kit.ModelConfig {
	return []kit.ModelConfig{
		{
			ID:              "claude-opus-4-7",
			Provider:        ProviderAnthropic,
			ContextWindow:   1_000_000,
			InputLimit:      1_000_000,
			OutputLimit:     128_000,
			KnowledgeCutoff: "2026-01-31",
			ReleaseDate:     "2026-04-16",
			Cost: kit.ModelCost{
				Input:      5,
				Output:     25,
				CacheRead:  0.5,
				CacheWrite: 6.25,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
		{
			ID:              "claude-sonnet-4-6",
			Provider:        ProviderAnthropic,
			ContextWindow:   1_000_000,
			InputLimit:      1_000_000,
			OutputLimit:     64_000,
			KnowledgeCutoff: "2025-08-31",
			ReleaseDate:     "2026-02-17",
			Cost: kit.ModelCost{
				Input:      3,
				Output:     15,
				CacheRead:  0.3,
				CacheWrite: 3.75,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
		{
			ID:              "claude-haiku-4-5",
			Provider:        ProviderAnthropic,
			ContextWindow:   200_000,
			InputLimit:      200_000,
			OutputLimit:     64_000,
			KnowledgeCutoff: "2025-02-28",
			ReleaseDate:     "2025-10-15",
			Cost: kit.ModelCost{
				Input:      1,
				Output:     5,
				CacheRead:  0.1,
				CacheWrite: 1.25,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
	}
}

func openaiModels() []kit.ModelConfig {
	return []kit.ModelConfig{
		{
			ID:            "gpt-5.5-pro",
			Provider:      ProviderOpenAI,
			ContextWindow: 1_050_000,
			InputLimit:    922_000,
			OutputLimit:   128_000,
			Cost: kit.ModelCost{
				Input:  30,
				Output: 180,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
			KnowledgeCutoff: "2025-12-01",
			ReleaseDate:     "2026-04-23",
		},
		{
			ID:              "gpt-5.5",
			Provider:        ProviderOpenAI,
			ContextWindow:   1_050_000,
			InputLimit:      922_000,
			OutputLimit:     128_000,
			KnowledgeCutoff: "2025-12-01",
			ReleaseDate:     "2026-04-23",
			Cost: kit.ModelCost{
				Input:     5,
				Output:    30,
				CacheRead: 0.5,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Batch:     true,
			},
		},
		{
			ID:              "gpt-5.4-mini",
			Provider:        ProviderOpenAI,
			ContextWindow:   400_000,
			InputLimit:      272_000,
			OutputLimit:     128_000,
			KnowledgeCutoff: "2025-08-31",
			ReleaseDate:     "2026-03-17",
			Cost: kit.ModelCost{
				Input:     0.75,
				Output:    4.5,
				CacheRead: 0.075,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
		{
			ID:              "gpt-5.4-nano",
			Provider:        ProviderOpenAI,
			ContextWindow:   400_000,
			InputLimit:      272_000,
			OutputLimit:     128_000,
			KnowledgeCutoff: "2025-08-31",
			ReleaseDate:     "2026-03-17",
			Cost: kit.ModelCost{
				Input:     0.2,
				Output:    1.25,
				CacheRead: 0.02,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
	}
}

func googleModels() []kit.ModelConfig {
	return []kit.ModelConfig{
		{
			ID:            "gemini-3.1-pro-preview",
			Provider:      ProviderGoogle,
			ContextWindow: 1_048_576,
			InputLimit:    1_048_576,
			OutputLimit:   65_536,
			Cost: kit.ModelCost{
				Input:     2,
				Output:    12,
				CacheRead: 0.2,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				Audio:     true,
				Video:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
			KnowledgeCutoff: "2025-01-01",
			ReleaseDate:     "2026-02-19",
		},
		{
			ID:            "gemini-3.1-flash-lite",
			Provider:      ProviderGoogle,
			ContextWindow: 1_048_576,
			InputLimit:    1_048_576,
			OutputLimit:   65_536,
			Cost: kit.ModelCost{
				Input:     0.25,
				Output:    1.5,
				CacheRead: 0.025,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				Audio:     true,
				Video:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
			KnowledgeCutoff: "2025-01-01",
			ReleaseDate:     "2026-05-07",
		},
		{
			ID:              "gemini-2.5-pro",
			Provider:        ProviderGoogle,
			ContextWindow:   1_048_576,
			InputLimit:      1_048_576,
			OutputLimit:     65_536,
			KnowledgeCutoff: "2025-01-01",
			ReleaseDate:     "2025-03-20",
			Cost: kit.ModelCost{
				Input:     1.25,
				Output:    10,
				CacheRead: 0.125,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				Audio:     true,
				Video:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
		{
			ID:              "gemini-2.5-flash",
			Provider:        ProviderGoogle,
			ContextWindow:   1_048_576,
			InputLimit:      1_048_576,
			OutputLimit:     65_536,
			KnowledgeCutoff: "2025-01-01",
			ReleaseDate:     "2025-03-20",
			Cost: kit.ModelCost{
				Input:     0.3,
				Output:    2.5,
				CacheRead: 0.03,
			},
			Capabilities: kit.ModelCapabilities{
				Text:      true,
				Image:     true,
				Audio:     true,
				Video:     true,
				PDF:       true,
				Tools:     true,
				Streaming: true,
				Reasoning: true,
				Caching:   true,
				Batch:     true,
			},
		},
	}
}
